### ISSUE TITLE
mintupdate 5.4.4: partly lost localization

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/mint-19.1-beta#51] opened 2018-12-10 15:09 UTC
**Bug description**
In mintupdate 5.4.4, part of the localization is lost. I checked this for Dutch, for which language Mint is fully translated on Launchpad (and has been so for a long time).
What I found was this:
In the panel of mintupdate, "Select" suddenly isn't localized. Also, the following items in the "Select" submenu aren't localized:
- All updates
- Level 1 updates
- Level 2 updates
- Level 3 updates
- Level 4 updates

**To Reproduce**
- Install Linux Mint 19.1 Tessa, Dutch localized, with a live internet connection so that all Dutch translations are being pulled.
- Launch mintupdate

**Expected behavior**
A fully Dutch translated user interface, including all submenu's.

**Frequency**
The issue happens always.

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [X] Xfce Edition
- Not checked in MATE, but likely to happen in that DE also.

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install

**Screenshots**

**Locale:**
Paste the output of `locale`.
LANG=nl_NL.UTF-8
LANGUAGE=nl_NL
LC_CTYPE="nl_NL.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_COLLATE="nl_NL.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="nl_NL.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=

**Drivers:**
Paste the output of `inxi -Gxx`.

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**

**Comment by NikoKrause** [comment] 2018-12-10 15:14
Duplicate of https://github.com/linuxmint/mint-19.1-beta/issues/25

**Closed as completed by NikoKrause** 2018-12-10 15:14 UTC
