### ISSUE TITLE
ubiquity: In Korean, fcitx is installed but misses recommends

### ISSUE THREAD

**Issue by bagjunggyu** [linuxmint/mint-19.1-beta#10] opened 2018-12-06 19:41 UTC
It is unavailabe to configure fcitx in native Linux Mint because of dropped packages for configuring fcitx
* fcitx-config-common
* fcitx-config-gtk
* fcitx-config-gtk2

it can be resolved by installing these 3 packages
$ apt install fcitx-config-common fcitx-config-gtk fcitx-config-gtk2

I hope it to be fixed from the native ISO.
Actually, It happened from 19 tara (now I've checked it)

And, also added here
When we install it manually by termnial or software manager, we can meet the same issue with it
$ apt install fcitx-hangul
There is no config tool for fcitx and even fcitx(IMF) itself.

If we want correct fcitx input method for Korean Hangul
we need these packages 

fcitx 
fcitx-bin 
fcitx-config-common                      
fcitx-config-gtk                         
fcitx-config-gtk2
fcitx-data  
fcitx-frontend-all     
fcitx-frontend-fbterm 
fcitx-frontend-gtk2
fcitx-frontend-gtk3  
fcitx-frontend-qt4       
fcitx-frontend-qt5
fcitx-hangul
fcitx-libs  
fcitx-module-dbus
fcitx-module-kimpanel 
fcitx-module-lua    
fcitx-module-x11     
fcitx-modules
fcitx-tools  
fcitx-ui-classic  
fcitx-ui-light 
fcitx-ui-qimpanel  
gir1.2-fcitx-1.0  
libfcitx-config4
libfcitx-core0
libfcitx-gclient1
libfcitx-qt0
libfcitx-qt5-1
libfcitx-utils0

it should be
$ apt install fcitx-hangul 
then, other packages should be installed by default with fcitx-hangul

I think this issue is happened from the package manage policy of software manager.
I hope it to be fixed as well
Thank you.

**Frequency**
Does the issue happen:
[0] Always
[ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
[0] Cinnamon Edition
[0] MATE Edition
[0] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
[0] Post-install
[x] Live session - no input method for live session whether switching(after installing it) language to Korean.

**Comment by ghost** [comment] 2018-12-10 00:31
Right after fresh install (fcitx is installed by default)
![2018-12-07 07-04-24](https://user-images.githubusercontent.com/2834031/49705047-47692a80-fc5e-11e8-9188-9e680df29def.png)

**Comment by ghost** [comment] 2018-12-10 00:32
Expected state
After Installing config tool packages
![2018-12-07 07-05-38](https://user-images.githubusercontent.com/2834031/49705065-7ed7d700-fc5e-11e8-87f9-caed2cb176b0.png)

**Comment by clefebvre** [comment] 2018-12-11 17:13
Hi @bagjunggyu,

I can reproduce the issue. It's a packaging issue and I'm not sure we'll be able to fix it this time around. It's not clear to me what's triggering the installation of fcitx during the installation, there's no ref to it in ubiquity. Anyhow these config packages are missing because they're not dependencies and we have recommends OFF by default.

Post-install mintlocale-im does the job though, it suggests the installation of the missing packages.

**Comment by ghost** [comment] 2018-12-11 21:33
@clefebvre Sad news but I can understand it now :)
That is enough at this time though, I hope it can be resolved later.
Thank you Clem :)
Merry Christmas~~

**Comment by ghost** [comment] 2018-12-11 22:26
But, My opinion is,
We need at least one Input Method by default after installing OS.
It could be fcitx or ibus  whatever though.
That is something like we have OS without English keyboard layout in your shoes.
I hope your reconsiderations of stance to Input Method :)
Thank you
and Merry Christmas :)

**Comment by clefebvre** [comment] 2018-12-11 23:31
I've an idea but I'm not sure it'll work. I'll try to implement it tomorrow.

**Comment by ghost** [comment] 2018-12-11 23:35
Nice!! I hope it would be!!

**Comment by gm10** [comment] 2018-12-12 00:00
> It's not clear to me what's triggering the installation of fcitx during the installation, there's no ref to it in ubiquity. 

@clefebvre ubiquity is a bit convoluted but my understanding is that fcitx gets installed here, suggest you patch the missing recommend in at the same place:
https://github.com/linuxmint/ubiquity/blob/master/d-i/source/localechooser/finish-install.d/05localechooser#L28

**Comment by clefebvre** [comment] 2018-12-12 08:14
@gm10 no, I added this section myself... and it didn't work :(

**Comment by gm10** [comment] 2018-12-12 08:33
@clefebvre oh lol, my bad, it was late and I didn't think you'd already looked into it at that time so I didn't even check. You might have to whitelist it like is done for the boot packages here or the manifest might override it:
https://github.com/linuxmint/ubiquity/blob/master/scripts/install.py#L271

**Comment by clefebvre** [comment] 2018-12-12 10:48
Fixed by https://github.com/linuxmint/ubiquity/commit/085017a2e8fe5093a629e1282e2368ac0ac238bd

**Closed by clefebvre** 2018-12-12 10:48 UTC
