### ISSUE TITLE
cinnamon: gwl: Non-Modal dialogs do not dissapear after removal (2 Monitor + 2 Panels issue)

### ISSUE THREAD

**Issue by Piiit** [linuxmint/mint-19.1-beta#49] opened 2018-12-10 10:25 UTC
**Describe the bug**
This is a 2 monitor, 2 panels with a GWL each setting. Inside GWL: set `Button label` to `Window title`

When I open a non-modal dialog from an application on the first monitor (the window count inside the group does not change - screenshot [1]) and drag the dialog to the second monitor, a new icon appears inside the GWL of the second monitor, but without title (screenshot [2]). 
When I drag it back to the first monitor, it does not dissapear (screenshot [3]). However, when I move the main window from the first monitor to the second and back again, the group gets activated on entry and the whole group dissapears when I move out.

**To Reproduce**
1. Configure a 2-monitor system with a panel on each monitor including GWL on both panels
2. Open xed > Tools > Document statistics (=non-modal dialog)
3. Move `Document statistics` from the first to the second monitor and back
4. The icon in GWL monitor-2 remains visible

**Expected behavior**
The icon inside GWL on monitor-2 should dissapear when dragging the non-modal dialog back to monitor-1. Related to that, when I set `Button label` to `Window title` also non-modal dialogs should show their title inside GWL.

**Frequency**
Does the issue happen:
- [x] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [x] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [x] Post-install
- [ ] Live session

**Screenshots**
Screenshot 1
![selection_018](https://user-images.githubusercontent.com/6096063/49726443-4cce7100-fc6e-11e8-9264-0c4d4051ff8a.png)

Screenshot 2
![selection_019](https://user-images.githubusercontent.com/6096063/49726451-5657d900-fc6e-11e8-9d7c-04f51f34bf0c.png)

Screenshot 3
![selection_020](https://user-images.githubusercontent.com/6096063/49726456-5b1c8d00-fc6e-11e8-843a-6033a800c7bc.png)

**Locale:**
Paste the output of `locale`.

**Drivers:**
Paste the output of `inxi -Gxx`.

**Crash report:**

''Stack trace''
If you are reporting a crash. Go to "Software Sources" and enable the debug symbols. Then go to "System Reports" and extract the stack trace for your crash and paste it here.

''Dmesg''
If you type `dmesg` in a terminal, you should see a line corresponding to the crash. Paste it here.

**Additional context**
Restarting cinnamon solves the problem with orphaned icons inside GWL.

**Comment by jaszhix** [comment] 2018-12-10 11:27
This is happening because the skip taskbar hint is set by the application for the dialog, so the only alternative to ignore that. We probably should respect the intent of the developer, and not index the window in GWL. 

I think this has previously only been an issue where dialogs become detached from their parent and get lost in the stack, but those are rare cases that can be fixed in the applications themselves. Xed's dialogs in particular don't have this issue.

**Comment by jaszhix** [comment] 2018-12-10 11:31
> However, when I move the main window from the first monitor to the second and back again, the group gets activated on entry and the whole group dissapears when I move out.

Sorry, missed this, there is an issue with the skip taskbar hint not being ignored fully with the per-monitor handling logic.

**Comment by Piiit** [comment] 2018-12-10 12:04
> This is happening because the skip taskbar hint is set by the application for the dialog, so the only alternative to ignore that. We probably should respect the intent of the developer, and not index the window in GWL.

I've set `Include all app windows` in ITM and would love to have that feature also in GWL, ignoring the advice of developers. 

![selection_021](https://user-images.githubusercontent.com/6096063/49731755-ab025080-fc7c-11e8-9655-f12544df1be2.png)

I think, the hint given by developers is useful, if someone disables that option, but not if someone likes to see all windows on their taskbar. I forget sometimes which sub-windows are open, or move a "search dialog" (for instance, in Eclipse) to another monitor. Would be nice to see on which monitor which windows are, regardless of main- or sub-windows. Is that feasible?

I would not expect that some sub-windows are shown and others not, due to their skip taskbar hint, hence an option could be useful here.

**Comment by jaszhix** [comment] 2018-12-10 12:17
The problem is this causes some windows to be buggy. Try using Virtualbox in ITM, and in GWL - there will be an overlay window that is all black that's not in the app group, and it can't be closed. The developer didn't intend for this to be seen and set the skip-taskbar hint. I too thought I wouldn't like the change, but I later realized most of these are just dialogs that are stuck to their parent, and there's not much use for them being in GWL as far as being able to locate them. 

Maybe the option could be added back later that blacklists some known buggy cases, but I think its too late for 4.0.

**Comment by Piiit** [comment] 2018-12-10 12:26
Got it, thanks for the explanation...

> Maybe the option could be added back later that blacklists some known buggy cases, but I think its too late for 4.0.

That would be really nice :-)

**Closed as completed** 2018-12-11 10:50 UTC
